version: "3"

includes:
  gh: ./taskfiles/github.yaml
  init: ./taskfiles/init.yaml

tasks:
  greet:
    cmd: echo 'Hello World from Task!'

  greet-var:
    cmd: echo {{ .GREETING }}
    vars:
      GREETING: "Hello!"

  greet-loop:
    cmds:
      - for: ["Good Morning!", "Good Afternoon!", "Good Evening!"]
        task: greet-var
        vars:
          GREETING: "{{ .ITEM }}"

  source-and-generate:
    cmd: cp Taskfile.yaml Taskfile.yaml.copy
    sources:
      - Taskfile.yaml
    generates:
      - Taskfile.yaml.copy

  check-status:
    cmd: echo 'something went wrong'
    status:
      - test -d .vscode
      - test -f Taskfile.yaml

  yes-or-no:
    prompt: Are you sure?
    cmd: echo 'You said yes'

  # Makefileの変更を監視してタスクを実行
  watch-makefile:
    cmd: echo 'Makefile changed!'
    watch: true
    sources:
      - Makefile
