version: "3"

includes:
  init: ./taskfiles/init.yaml

tasks:
  greet:
    cmds:
      - echo 'Hello World from Task!'

  greet-var:
    cmds:
      - echo {{ .GREETING }}
    vars:
      GREETING: "Hello!"

  greet-loop:
    cmds:
      - for: ["Good Morning!", "Good Afternoon!", "Good Evening!"]
        task: greet-var
        vars:
          GREETING: "{{ .ITEM }}"

  source-and-generate:
    cmds:
      - cp Taskfile.yaml Taskfile.yaml.copy
    sources:
      - Taskfile.yaml
    generates:
      - Taskfile.yaml.copy

  check-status:
    cmds:
      - echo 'something went wrong'
    status:
      - test -d .vscode
      - test -f Taskfile.yaml

  yes-or-no:
    prompt: Are you sure?
    cmds:
      - echo 'You said yes'