version: "3"

includes:
  init: ./taskfiles/init.yaml

tasks:
  greet:
    cmds:
      - echo 'Hello World from Task!'

  greet-var:
    cmds:
      - echo {{ .GREETING }}
    vars:
      GREETING: "Hello!"

  greet-loop:
    cmds:
      - for: ["Good Morning!", "Good Afternoon!", "Good Evening!"]
        task: greet-var
        vars:
          GREETING: "{{ .ITEM }}"
