version: "3"

includes:
  subtask1: ./my-task.yaml

tasks:
  init:
    cmds:
      - task: setup-completion

  setup-completion:
    cmds:
      - curl -sSfL -o /home/ubuntu/.config/fish/completions/task.fish https://raw.githubusercontent.com/go-task/task/main/completion/fish/task.fish
    status:
      - test -f ~/.config/fish/completions/task.fish
