version: "3"

includes:
  init: ./taskfiles/init.yaml

tasks:
  greet:
    cmds:
      - echo 'Hello World from Task!'

  greet_var:
    cmds:
      - echo {{ .GREETING }}
    vars:
      GREETING: "Hello!"
